name: &name dojang
version: 0.2.0
synopsis: A cross-platform dotfiles manager
description: See also the README.md file.
homepage: https://dojang.dev/
license: GPL-3.0-or-later
author: &author Hong Minhee <hong@minhee.org>
maintainer: *author
copyright: "\xa9 2023 Hong Minhee"
category: Configuration

extra-doc-files:
- README.md
- CHANGES.md
- LICENSE

flags:
  static:
    description: Static link
    manual: true
    default: false

dependencies:
  base: ">=4.7 && <5"
  bytestring: ">=0.11 && <0.13"
  case-insensitive: ">=1.2.1.0 && <2"
  containers: ">0"
  Diff: ">=0.4.1 && <1.1"
  directory: ">=1.3.8 && <1.4"
  filepath: ">=1.4.100 && <2"
  hashable: ">=1.4.2.0 && <2"
  megaparsec: ">=9.3 && <10"
  monad-logger: ">=0.3 && <0.4"
  mtl: ">=2.3 && <3"
  optparse-applicative: ">=0.17 && <0.19"
  text: ">=2 && <3"
  text-show: ">=3 && <4"
  toml-parser: ">=1.3 && <2"
  unordered-containers: ">=0.2.19.1 && <1"
  pretty-terminal: ">=0.1 && <0.2"

ghc-options:
# cSpell:disable
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
# cSpell:enable

library:
  source-dirs: src
  dependencies:
    deepseq: ">=1.4 && <2"
    extra: ">=1.7 && <2"
    filepattern: ">=0.1.3 && <2"
    fortytwo: ">=2 && < 2.1"
    parser-combinators: ">=1 && <2"
    process: ">=1.6 && <2"
    semver: ">=0.4 && <0.5"
  ghc-options:
  # cSpell:disable
  - -Wmissing-export-lists
  # cSpell:enable

executables:
  dojang:
    source-dirs: app
    main: Main.hs
    dependencies:
      # cSpell:disable
      *name : ">0"
      code-page: ">=0.2 && <0.3"
      # cSpell:enable
    when:
    - condition: flag(static)
      then:
        when:
        - condition: os(linux)
          then:
            ghc-options:
            # cSpell:disable
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wno-incomplete-uni-patterns
            # See also: https://github.com/commercialhaskell/stack/issues/3918
            - -optP-Wno-nonportable-include-path
            # Static link (Linux)
            - -static
            - -optl-static
            - -optl-pthread
            - -optc-Os
            - -fPIC
            # cSpell:enable
          else:
            ghc-options:
            # cSpell:disable
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wno-incomplete-uni-patterns
            # See also: https://github.com/commercialhaskell/stack/issues/3918
            - -optP-Wno-nonportable-include-path
            # Static link (non-Linux)
            - -static
            - -optc-Os
            # cSpell:enable
      else:
        ghc-options: &executable-ghc-options
        # cSpell:disable
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -Wno-incomplete-uni-patterns
        # See also: https://github.com/commercialhaskell/stack/issues/3918
        - -optP-Wno-nonportable-include-path
        # cSpell:enable

tests:
  spec:
    main: Main.hs
    source-dirs: test
    ghc-options: *executable-ghc-options
    dependencies:
      *name : ">0"
      # cSpell:disable
      hedgehog: ">=1.2 && <2"
      hspec: ">=2.10.10 && <2.12"
      hspec-api: ">=2.10 && <2.12"
      hspec-discover: ">=2.10.10 && <2.12"
      hspec-expectations-pretty-diff: ">=0.7 && <0.8"
      hspec-hedgehog: ">=0.0.1.2 && <0.4"
      hspec-junit-formatter: ">=1.1.0.2 && <1.2"
      hspec-megaparsec: ">=2.2 && <2.3"
      os-string: ">=2 && <3"
      random: ">=1.2 && <2"
      regex-tdfa: "^>= 1.3.2"
      temporary: ">=1.3 && <1.4"
      # cSpell:enable
