resolver: lts-21.19
require-stack-version: ">=2.11.1"
packages:
- .
extra-deps:
- ansi-terminal-1.0
- Cabal-3.8.1.0
- Cabal-syntax-3.8.1.0
- code-page-0.2.1
- directory-1.3.8.1
- exceptions-0.10.7
- filepath-1.4.100.4
- fortytwo-2.0.0
- hedgehog-1.4
- mtl-2.3.1
- parsec-3.1.17.0
- process-1.6.16.0
- terminal-size-0.3.3
- time-1.12.2
- toml-parser-1.3.0.0
- unix-2.8.2.1
- Win32-2.13.4.0
ghc-options:
  # cSpell:disable
  "$everything": -j4 +RTS -A32m -RTS -haddock
  "$locals": -Werror -fhide-source-paths
  # cSpell:enable
