resolver: lts-24.28
require-stack-version: ">=2.11.1"
packages:
- .
allow-newer: true
allow-newer-deps:
- fortytwo
- toml-parser
extra-deps:
- fortytwo-2.0.0@sha256:230310f5b8cdcd3b9f2a65b7d0d7bf38a14a2c98e9d88efd56068da60bcc70c7,2664
- terminal-size-0.3.3
- toml-parser-1.3.2.0@sha256:50adac7c438c0217e5968646618d5316c3c74f9c14e036976999f9b90a612306,3625
ghc-options:
  # cSpell:disable
  "$everything": -j4 +RTS -A32m -RTS -haddock
  "$locals": -Werror -fhide-source-paths
  # cSpell:enable
